[theme]
base = "dark"
primaryColor = "#FFFFFF"
backgroundColor = "#004D26"          # verde escuro (fundo)
secondaryBackgroundColor = "#0A5A33" # verde para cards/inputs
textColor = "#FFFFFF"                # textos brancos
